# Generated by Django 5.2.9 on 2026-01-20 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cost_category', '0001_initial'),
        ('cost_month', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycostcategory',
            name='monthly_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_category_items', to='cost_month.monthlyfinancialsummary'),
        ),
        migrations.AddIndex(
            model_name='costcategory',
            index=models.Index(fields=['business'], name='bma_cost_ca_busines_f074e5_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlycostcategory',
            index=models.Index(fields=['monthly_summary'], name='bma_monthly_monthly_a7a028_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlycostcategory',
            constraint=models.UniqueConstraint(fields=('monthly_summary', 'cost_category'), name='uniq_month_cost_category'),
        ),
    ]
