# Generated by Django 5.2.9 on 2026-01-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('haveEquity', models.IntegerField(blank=True, default=0, null=True)),
                ('assets', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bma_business',
            },
        ),
    ]
