# Generated by Django 5.2.9 on 2026-01-20 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_app', '0002_initial'),
        ('product', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyFinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('products_total_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('net_profit_before_tax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('net_profit_after_tax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('gross_profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('salary_expenditure', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('input_gst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('output_gst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('gst_payable', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('invoice_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_app.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bma_monthly_financial_summary',
            },
        ),
        migrations.CreateModel(
            name='MonthlyProductPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_performance', to='cost_month.monthlyfinancialsummary')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
            options={
                'db_table': 'bma_monthly_product_performance',
            },
        ),
        migrations.AddIndex(
            model_name='monthlyfinancialsummary',
            index=models.Index(fields=['business', 'year', 'month'], name='bma_monthly_busines_b7b4dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlyfinancialsummary',
            constraint=models.UniqueConstraint(fields=('business', 'year', 'month'), name='uniq_business_month_year'),
        ),
        migrations.AddIndex(
            model_name='monthlyproductperformance',
            index=models.Index(fields=['monthly_summary'], name='bma_monthly_monthly_5a8e52_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlyproductperformance',
            constraint=models.UniqueConstraint(fields=('monthly_summary', 'product'), name='uniq_month_product'),
        ),
    ]
