# Generated by Django 5.2.9 on 2026-01-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_month', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyproductperformance',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlyproductperformance',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
