from bma.config import environment_variable

#celery
CELERY_BROKER_URL =environment_variable.CELERY_BROKER_URL
CELERY_RESULT_BACKEND =environment_variable.CELERY_RESULT_BACKEND

CELERY_ACCEPT_CONTENT =environment_variable.CELERY_ACCEPT_CONTENT
CELERY_TASK_SERIALIZER = environment_variable.CELERY_TASK_SERIALIZER

CELERY_TIMEZONE =environment_variable.CELERY_TIMEZONE
CELERY_TASK_TRACK_STARTED = environment_variable.CELERY_TASK_TRACK_STARTED
CELERY_TASK_TIME_LIMIT =environment_variable.CELERY_TASK_TIME_LIMIT
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
